export default{
  "appName": "CardOrganiser",
  "vault": "server",
  "agent": "browser",
  "system":   "any",
  "browser":  "any",
  "mode":  "autologin",
  "stage":  "release",
  "vaultDomain":  "vault",
  "didDomain":  "vault",
  "enclaveType": "WalletDBEnclave",
  "sw": false,
  "pwa": false,
  "allowPinLogin": false,
}
